[package]
name = "DeepIron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
path = "0.8.2"
polars = "0.34.2"
